from src.state.state import AgentState
from src.tools.mcp_server import interact_with_ui
import time

def executor_agent(state: AgentState) -> dict:
    """
    Executes the tool calls generated by the Engineer.
    """
    print("[Executor] Executing test steps...")
    current_test_context = state.get("current_test_context", {})
    execution_plan = current_test_context.get("execution_plan", [])
    logs = []
    screenshots = []

    # If we are retrying, we might want to start from the failed step or just retry the whole scenario.
    # For simplicity, we'll retry the whole scenario or just proceed.

    for i, step in enumerate(execution_plan):
        tool_name = step.get("tool")
        args = step.get("args")

        print(f"[Executor] Running step {i+1}: {args['action']} {args['description']}")

        try:
            # Call the tool directly (mocking tool call execution)
            if tool_name == "interact_with_ui":
                result = interact_with_ui.invoke(args)

                logs.append(f"Step {i+1}: {result['message']}")
                if result.get('screenshot'):
                    screenshots.append(result['screenshot'])

                if not result['success']:
                    # Failure detected
                    print(f"[Executor] Step failed: {result['message']}")
                    return {
                        "execution_logs": logs,
                        "screenshots": screenshots,
                        "error": result['message'],
                        "current_test_context": {"failed_step_index": i, "execution_plan": execution_plan}, # Preserve context
                        "final_verdict": "failed" # Tentative, can be healed
                    }
        except Exception as e:
            print(f"[Executor] Exception: {str(e)}")
            return {
                "execution_logs": logs,
                "error": str(e),
                "final_verdict": "failed"
            }

    return {
        "execution_logs": logs,
        "screenshots": screenshots,
        "error": None,
        "final_verdict": "passed" # Tentative, pending evaluation
    }
